version: "3.2"
services:
    phpplay:
        build:
            dockerfile: Dockerfile
            context: ./
        ports:
            - 8073:80
        environment:
            - SIGN_URL=http://localhost:8074
            - RETURN_URL=http://localhost:8073/saml.php

    phpplayauth:
        build:
            dockerfile: Dockerfile-auth
            context: ./
        ports:
            - 8074:80                    