FROM alpine:latest

RUN apk update
#RUN apk upgrade
RUN apk add --no-cache apache2 php7-apache2 php7-pear php7-dev gcc musl-dev make

RUN pecl channel-update pecl.php.net

#RUN pecl install xdebug
RUN pecl install -o -f redis

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
RUN rm /var/www/localhost/htdocs/index.html
COPY src/ /var/www/localhost/htdocs

EXPOSE 80

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]